export const listHousesMock = [
  {
    id: 1,
    description: 'Descrição do imóvel',
    city: 'São Pedro',
    neighborhood: 'bairro',
    street: 'rua',
    number: 'número F',
    price: '350.000,00',
    area: '5000',
    seller: 'Cirilo',
    owner: 'Glasi',
  },
  {
    id: 2,
    description: 'Descrição do imóvel',
    city: 'São Pedro',
    neighborhood: 'bairro',
    street: 'rua',
    number: 'número F',
    price: '350.000,00',
    area: '5000',
    seller: 'Cirilo',
    owner: 'Glasi',
  },
];
